/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import io.spine.gradle.internal.Deps

buildscript {
    apply(from = "$rootDir/config/gradle/dependencies.gradle")
}

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.72")

    // Apply the application plugin to add support for building a CLI application.
    application
    jacoco
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.eclipse.jgit:org.eclipse.jgit:2.2.0.201212191850-r")

    // A JSON library.
    implementation("com.beust:klaxon:5.4")
    implementation("com.auth0:java-jwt:3.10.3")

    // A crypto library to help sign JWTs.
    implementation("org.bouncycastle:bcpkix-jdk15on:1.66")

    implementation(Deps.build.googleHttpClient)

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.0.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.6.2")

    // A fluent assertions library.
    testImplementation("com.willowtreeapps.assertk:assertk-jvm:0.22")
}

application {
    // Define the main class for the application
    mainClassName = "io.spine.publishing.Application"
}

tasks.test {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}
tasks.jacocoTestReport {
    dependsOn(tasks.test)
}
